import { StyleSheet } from 'react-native';
const SCAN_AREA_SIZE = 280;

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#000' },
    loadingContainer: { flex: 1, backgroundColor: '#000', justifyContent: 'center', alignItems: 'center' },
    restrictedContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 40,
    },
    restrictedTitle: {
        fontSize: 24,
        fontFamily: 'Ubuntu_Bold',
        color: '#FFF',
        marginTop: 24,
        marginBottom: 12,
        textAlign: 'center',
    },
    restrictedText: {
        fontSize: 14,
        fontFamily: 'Ubuntu_Regular',
        color: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
        marginBottom: 32,
        lineHeight: 22,
    },
    restrictedButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: '#FFF',
        paddingVertical: 14,
        paddingHorizontal: 32,
        borderRadius: 30,
    },
    restrictedButtonText: { fontSize: 16, fontFamily: 'Ubuntu_Bold', color: '#000' },
    camera: { flex: 1 },
    overlay: { flex: 1 },
    closeButton: {
        position: 'absolute',
        left: 20,
        zIndex: 10,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    torchButton: {
        position: 'absolute',
        right: 20,
        zIndex: 10,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    overlayTop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)' },
    scanRow: { flexDirection: 'row', height: SCAN_AREA_SIZE },
    overlaySide: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)' },
    scanArea: {
        width: SCAN_AREA_SIZE,
        height: SCAN_AREA_SIZE,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    scanLine: {
        position: 'absolute',
        width: SCAN_AREA_SIZE - 60,
        height: 2,
        backgroundColor: '#4CAF50',
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
    },
    gridContainer: { position: 'absolute', width: '100%', height: '100%' },
    gridLineVertical: { position: 'absolute', width: 1, height: '100%', backgroundColor: 'rgba(255,255,255,0.2)' },
    gridLineHorizontal: { position: 'absolute', width: '100%', height: 1, backgroundColor: 'rgba(255,255,255,0.2)' },
    corner: { position: 'absolute', width: 30, height: 30, borderColor: '#FFF', borderWidth: 4 },
    topLeft: { top: 0, left: 0, borderRightWidth: 0, borderBottomWidth: 0 },
    topRight: { top: 0, right: 0, borderLeftWidth: 0, borderBottomWidth: 0 },
    bottomLeft: { bottom: 0, left: 0, borderRightWidth: 0, borderTopWidth: 0 },
    bottomRight: { bottom: 0, right: 0, borderLeftWidth: 0, borderTopWidth: 0 },
    overlayBottom: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', paddingTop: 40 },
    instructionContainer: { alignItems: 'center', paddingHorizontal: 40 },
    instructionTitle: { fontSize: 20, fontFamily: 'Ubuntu_Bold', color: '#FFF', textAlign: 'center', marginBottom: 8 },
    instructionText: { fontSize: 14, fontFamily: 'Ubuntu_Regular', color: 'rgba(255,255,255,0.8)', textAlign: 'center', marginBottom: 20 },
    rescanButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', paddingVertical: 12, paddingHorizontal: 24, borderRadius: 25, gap: 8 },
    rescanButtonActive: { backgroundColor: '#1776BA' },
    rescanButtonText: { fontSize: 16, fontFamily: 'Ubuntu_Medium', color: '#000' },
    rescanButtonTextActive: { color: '#FFF' },
    loadingScanProcess: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
        backgroundColor: 'rgba(0,0,0,0.9)',
    },
    loadingText: { fontSize: 16, fontFamily: 'Ubuntu_Medium', color: '#FFF', marginTop: 16 },
    permissionContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 40 },
    permissionTitle: { fontSize: 24, fontFamily: 'Ubuntu_Bold', color: '#FFF', marginTop: 24, marginBottom: 12, textAlign: 'center' },
    permissionText: { fontSize: 14, fontFamily: 'Ubuntu_Regular', color: 'rgba(255,255,255,0.7)', textAlign: 'center', marginBottom: 32, lineHeight: 22 },
    permissionButton: { backgroundColor: '#FFF', paddingVertical: 14, paddingHorizontal: 32, borderRadius: 30 },
    permissionButtonText: { fontSize: 16, fontFamily: 'Ubuntu_Bold', color: '#000' },
});