import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    mapContainer: {
        flex: 1,
        borderRadius: 12,
        overflow: "hidden",
        position: "relative",
    },
    map: {
        flex: 1,
    },
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 20,
        gap: 12,
    },
    loadingText: {
        fontSize: 16,
        fontFamily: "Ubuntu_Regular",
    },
    header: {
        position: "absolute",
        paddingHorizontal: 15,
        top: 52,
        left: 0,
        right: 0,
        width: "100%",
        height: 60,
        zIndex: 10,
    },
    headerContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    headerButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    controlButtonsContainer: {
        position: "absolute",
        bottom: 120,
        right: 20,
        flexDirection: "column",
        gap: 12,
        zIndex: 15,
    },
    controlButton: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    floatingButtonContainer: {
        position: "absolute",
        bottom: 20,
        left: 20,
        right: 20,
        alignItems: "center",
        zIndex: 5,
    },
    floatingButton: {
        backgroundColor: "#1776BA",
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 30,
        minWidth: 200,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
        elevation: 8,
    },
    floatingButtonActive: {
        backgroundColor: "#E74C3C",
    },
    floatingButtonText: {
        color: "#FFFFFF",
        fontSize: 16,
        fontFamily: "Ubuntu_Bold",
    },
    boardingIndicator: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#5856D6",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
        marginBottom: 12,
        gap: 8,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    boardingIndicatorText: {
        color: "#FFFFFF",
        fontSize: 14,
        fontFamily: "Ubuntu_Medium",
    },
    bottomSheetOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "flex-end",
    },
    bottomSheetContent: {
        width: "100%",
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingTop: 12,
        paddingBottom: 34,
        paddingHorizontal: 24,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: -4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    bottomSheetHandle: {
        width: 40,
        height: 4,
        backgroundColor: "#C7C7CC",
        borderRadius: 2,
        alignSelf: "center",
        marginBottom: 24,
    },
    bottomSheetTitle: {
        fontSize: 20,
        fontFamily: "Ubuntu_Bold",
        marginBottom: 16,
        textAlign: "center",
    },
    bottomSheetMessage: {
        fontSize: 16,
        fontFamily: "Ubuntu_Regular",
        marginBottom: 24,
        textAlign: "center",
        lineHeight: 22,
    },
    bottomSheetButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 16,
        paddingHorizontal: 24,
        borderRadius: 12,
        marginBottom: 12,
        gap: 12,
    },
    bottomSheetButtonText: {
        color: "#FFFFFF",
        fontSize: 16,
        fontFamily: "Ubuntu_Medium",
    },
    bottomSheetCloseButton: {
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 12,
        marginTop: 8,
        alignItems: "center",
    },
    bottomSheetCloseText: {
        fontSize: 16,
        fontFamily: "Ubuntu_Medium",
    },
    confirmButtonsContainer: {
        gap: 12,
    },
    bottomSheetConfirmButton: {
        paddingVertical: 16,
        paddingHorizontal: 24,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    bottomSheetConfirmButtonText: {
        color: "#FFFFFF",
        fontSize: 16,
        fontFamily: "Ubuntu_Medium",
    },
    loaderContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
});